WebClient.BookStore/WebClient.BookStore/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebClient.BookStore.Areas.Admin.Controllers
{
    [Area("admin")]
    //[Route("admin/[controller]/[action]")]
    [Route("admin")]
    public class HomeController : Controller
    {

        //http://localhost:65267/admin
        // GET: HomeController
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }

        //http://localhost:65267/admin/home/details/1
        // GET: HomeController/Details/5
        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: HomeController/Create
        [Route("create")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [Route("create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        [Route("edit/id")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit/id")]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        [Route("delete/id")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("delete/id")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebClient.BookStore/WebClient.BookStore/Areas/Financial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebClient.BookStore.Areas.Financial.Controllers
{
    [Area("financial")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebClient.BookStore/WebClient.BookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebClient.BookStore.Repository;

namespace WebClient.BookStore.Components
{
    public class TopBooksViewComponent :ViewComponent
    {
        private readonly IBookRepository _bookRepository = null;
        public TopBooksViewComponent(IBookRepository bookRepository) {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count) {

            var books=await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

WebClient.BookStore/WebClient.BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebClient.BookStore.Models;
using System.Dynamic;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using WebClient.BookStore.Repository;
using WebClient.BookStore.Service;
using Microsoft.AspNetCore.Authorization;

namespace WebClient.BookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IConfiguration _configuration = null;
        private readonly NewBookAlertMessageConfig _newBookIOption = null;
        private readonly NewBookAlertMessageConfig _externalBookIOption = null;
        private readonly IMessageRepository _messageRepository = null;

        private readonly IEmailService _emailService = null;

        private readonly IUserService _userService;
        public HomeController(
            IOptionsSnapshot<NewBookAlertMessageConfig> newBookIOption,
            IConfiguration configuration,
            IMessageRepository messageRepository,
            IUserService userService,
            IEmailService emailService)
        {
            _configuration = configuration;
            _newBookIOption = newBookIOption.Get("NewBook");
            _externalBookIOption = newBookIOption.Get("ExternalBook");
            _messageRepository = messageRepository;
            _userService = userService;
            _emailService = emailService;
        }
        //http://localhost:65267/
        public async Task<ViewResult> Index()
        {

            //UserEmailOptions options = new UserEmailOptions()
            //{
                //ToMails = new List<string>() { "ela.ars@gmail.com" },
                //PlaceHolders = new List<KeyValuePair<string, string>>()
                //{
                    //new KeyValuePair<string,string>("{{UserName}}","Elavarsan Kannayiram")
                //}
            //};
            //await _emailService.SendTestEmail(options);



            //Getting login details from service
            var userId = _userService.GetUserId();
            var isAuthenticated = _userService.IsAuthenticated();

            ViewBag.Title = "Welcome to Bookstore";
            ViewBag.SampleModel = new BookModel()
            {
                Id = 7,
                Author = "Rabindranath Tagore",
                Description = "National Anthem"
            };
            dynamic data = new ExpandoObject();
            data.Name = "Sachin";
            data.Sports = "Cricket";
            data.Country = "India";
            ViewBag.Data = data;
            return View();
        }

        //http://localhost:65267/home/AboutUs
        public ViewResult AboutUs()
        {
            //Using IOptions Snapshot with named Config
            bool newBookShowMessage = _newBookIOption.ShowMessage;
            string newBookAlertMessage = _newBookIOption.AlertMessage;

            bool externalBookShowMessage = _externalBookIOption.ShowMessage;
            string externalBookAlertMessage = _externalBookIOption.AlertMessage;

            //Using IOption Monitor method configuration
            var getName = _messageRepository.GetName();

            //Using IOption method configuration

            bool showMsg = _newBookIOption.ShowMessage;
            string alertMsg = _newBookIOption.AlertMessage;


            var key1 = _configuration["Keys:Key1"];
            var key2 = _configuration["Keys:Key2"];
            var key3 = _configuration["Keys:Key3:Name"];

            var ShowMessage = _configuration.GetValue<bool>("NewBookAlertMessage:ShowMessage");
            var AlertMessage = _configuration.GetValue<string>("NewBookAlertMessage:AlertMessage");

            var newBook = _configuration.GetSection("NewBookAlertMessage");
            var sMessage = newBook.GetValue<bool>("ShowMessage");
            var aMessage = newBook.GetValue<string>("AlertMessage");

            //or
            var showM = _configuration.GetSection("NewBookAlertMessage").GetValue<bool>("ShowMessage");

            //Binding configuration

            /*var newBookAlert = new NewBookAlertMessageConfig();
            _configuration.Bind("NewBookAlertMessage", newBookAlert);
            bool sm = newBookAlert.ShowMessage;
            string am = newBookAlert.AlertMessage;*/





            ViewBag.Title = "Welcome to About Us";
            ViewData["myData"] = new BookModel() { Id = 10, Title = "Sample Book", Description = "Sample Description for View Data", Author = "Vijay" };
            return View();
        }

        //http://localhost:65267/home/contactus


        //multiple roles can be assigned as like below
        //[Authorize(Roles = "Admin,User,Manager")]
        [Authorize(Roles ="Admin")]
        public ViewResult ContactUs()
        {
            ViewData["Name"] = "Elavarasan Kannayiram";

            return View();
        }

        //http://localhost:65267/home/mypage
        public ViewResult MyPage()
        {
            //full path
            // return View("TempView/MyPage.cshtml");
            // or
            //return View("~/TempView/MyPage.cshtml");

            //relative path
            return View("../../TempView/MyPage");
        }

        //Specific data
        [ViewData]
        public string viewDataString { get; set; }

        //Complex data
        [ViewData]
        public BookModel book { get; set; }

        [ViewData]
        public string BrowserTitle { get; set; }

        //http://localhost:65267/home/branches
        public ViewResult Branches()
        {
            viewDataString = "This string is comming from action as viewdataattribute";
            book = new BookModel()
            {
                Id = 33,
                Title = "My Sample book",
                Description = "This is created for sample book to demonstrate viewdataattribute complex data"
            };
            BrowserTitle = "This title action to layout";
            return View();
        }
    }
}

WebClient.BookStore/WebClient.BookStore/Views/Home/AboutUs.cshtml
@*@{
        Layout = "_Layout";
    }*@

@section pageName{
    <h2>About Us</h2>
}
@{
    ViewData["BrowserTitle"] = "About Us";
    var getData = ViewData["myData"] as BookModel;
}
<div class="row" style="display:block;margin:0;">
    <div>@getData.Id</div>
    <div>@getData.Title</div>
    <div>@getData.Description</div>
    <div>@getData.Author</div>
</div>
<h3>We are located all over the world!</h3>

WebClient.BookStore/WebClient.BookStore/Views/Home/Branches.cshtml
@{

    //Layout = null;
    //ViewData["BrowserTitle"] = "Branches";

    var book = ViewData["book"] as BookModel;
}


<div class="container">
    <div class="row">
    @section pageName{
        <h2>Branches</h2>
    }
    </div>
    <div class="row" style="margin:0;">
        @ViewData["viewDataString"]
    </div>
    <div class="row" style="margin:0">
        <div class="text-primary">
            <div>Id: @book.Id</div>
            <div>Title: @book.Title</div>
            <div>Description: @book.Description</div>
        </div>
        
    </div>
    <div class="row">
        <ul>
            <li class="text-danger">Bengaluru</li>
            <li class="text-primary">Chennai</li>
            <li class="text-success">Mumbai</li>
            <li class="text-warning">Noida</li>
            <li class="text-info">Pondicherry</li>
        </ul>
    </div>
</div>

WebClient.BookStore/WebClient.BookStore/Views/Home/Index.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration _config
@inject WebClient.BookStore.Repository.IBookRepository _bookRepo
@*@inject Microsoft.Extensions.Options.IOptions<NewBookAlertMessageConfig> _newBookIOptions*@
@inject Microsoft.Extensions.Options.IOptionsSnapshot<NewBookAlertMessageConfig> _newBookIOptions

@*@{
        var newBook = _config.GetSection("NewBookAlertMessage");
    }*@


@{
    var newBook = new NewBookAlertMessageConfig();
    _config.Bind("NewBookAlertMessage", newBook);

    var newBookIOptions = _newBookIOptions.Get("NewBook");
    var externalBookIOptions = _newBookIOptions.Get("ExternalBook");
}



@*@{
        Layout = "_Layout";
    }*@

@{
    ViewData["BrowserTitle"] = "Home";
}
    ViewData["BrowserTitle"] = "Branches";

@*
    <!--<h2>Welcome to book store application</h2>
    <h3 style="color:green">This is the home page of the book store application</h3>
    <h4 style="color:orangered">@DateTime.Now.ToString("dd-MM-yyyy")</h4>
    <h3>Single line</h3>
    <h4>Sum=@(5+6)</h4>
    <h3>Multi line</h3>
    @{
        int a = 10;
        int b = 44;
        int c = a + b;
    }
    <h4>Total=@c</h4>
    <h4>My email is : ela.ars@gmail.com</h4>
    <h3>Escape Sequence</h3>
    <h4>Twitter Account: @@elavarasan</h4>-->

    <h2 style="color:darkgoldenrod">Conditional statements</h2>
    <h3>If Statement</h3>
    @{
        int x = 10;
    }

    @if (x == 10)
    {<h4>x is equal to @x</h4>}
    <h3>If else Statement</h3>
    @{
        int s = 20;
        int t = 22;
    }
    @if (s + t > 50)
    {
        <h4>The sum (@(s + t)) of the value is less than 50</h4>
    }
    else
    {
        <h4>The sum (@(s + t)) of the value is greater than 50</h4>
    }
    <h3>If else if else Statement</h3>
    @{
        int q = 32;
        int r = 45;
        int st = q + r;
    }
    @if (st == 10)
    {
        <h4>The sum of value=@st is equal to 10</h4>
    }
    else if (st > 10 && st < 20)
    {
        <h4>The sum of value=@st is greater than 10 and less than 20</h4>
    }
    else
    {
        <h4>The sum of value=@st is greater than 20</h4>
    }

    <h3>Swith case</h3>
    @{
        int val = 3;
    }
    @switch (val)
    {
        case 1:<h2>@val : One </h2> break;
        case 2: <h2>@val : Two </h2>break;
        case 3: <h2>@val : Three </h2>break;
        case 4: <h2>@val : Four </h2>break;
        case 5: <h2>@val : Five </h2>break;
        default: <h2>Not in the list </h2>break;
     }
    <h3>Ternary Operator</h3>
    @{
        string status = "m";
    }
    <h4>Marital Status: @(status == "M"?"Married":"Single")</h4>
    <h2>Loops</h2>
    <h3>For loop</h3>
    @for (int i = 0; i <= 4; i++) {
        <h4>This is from for loop condition: @i</h4>
    }
    @{
        var list = new List<int>() { 11,12, 13,14, 15 };

    }
    <h3>foreach loop</h3>
    @foreach (var item in list) {
        <h4>This text is from for each loop: @item</h4>
    }
    <h3>Showing Image from wwwroot folder</h3>
    <img src="~/images/logo.png" class="logo" alt="logo" />

    <h3>Showing image from other folder</h3>
    <img src="~/MyStaticFiles/Desert.jpg" class="desert" alt="desert" />

    <h3>Bootstrap checking</h3>
    <button id="clickme" class="btn btn-danger btn-md">Click me</button>
*@

<section class="jumbotron text-center">
    <div class="container">
        <h1>@ViewBag.Title</h1>

        @*
        @if ((_config.GetValue<bool>("NewBookAlertMessage:ShowMessage")))
        {
            <div class="alert alert-success">
                <h3>@(_config.GetValue<string>("NewBookAlertMessage:AlertMessage"))</h3>
            </div>
        }
        *@

        @*@if ((newBook.GetValue<bool>("ShowMessage")))
        {
            <div class="alert alert-success">
                <h3>@(newBook.GetValue<string>("AlertMessage"))</h3>
            </div>
        }*@

        <!--binding configuration-->
        @*@if (newBook.ShowMessage)
        {
            <div class="alert alert-success">
                <h3>@newBook.AlertMessage</h3>
            </div>
        }*@

        <!--Using IOptions Model Configuration-->

        @if (newBookIOptions.ShowMessage)
        {
            <div class="alert alert-success">
                <h3>@newBookIOptions.AlertMessage</h3>
            </div>
        }

        @if (externalBookIOptions.ShowMessage)
        {
            <div class="alert alert-success">
                <h3>@externalBookIOptions.AlertMessage</h3>
            </div>
        }


        
        <p big>This is custom tag big Attribute</p>
        <big>This is custom big Tag element</big>

        <h1 style="color:darkorchid">@_config["SampleText"]</h1>

        <div class="text-danger font-weight-bold" style="font-size:30px;">
            <environment names="Production,Staging">Production Content using name attribute</environment>
            <environment names="Development">Development Content using name attribute</environment>
            <environment include="Production,Staging">Production Content using include attribute</environment>
            <environment include="Development">Development Content using include attribute</environment>
        </div>
        <h4>Id:@ViewBag.SampleModel.Id</h4>
        <h4>Authore:@ViewBag.SampleModel.Author</h4>
        <h4>Authore:@ViewBag.SampleModel.Description</h4>

        <div class="row">
            <span>Name: @ViewBag.Data.Name </span>
            <span>Sports: @ViewBag.Data.Sports </span>
            <span>Country: @ViewBag.Data.Country </span>
        </div>
        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut aliquam magna. Curabitur tempor eu justo id volutpat. In hac habitasse platea dictumst. Proin imperdiet dui augue.
        </p>
        <p>
            <a href="" class="btn btn-primary my-2" id="clickme">Search books</a>
        </p>

    </div>
    <div class="container">

        @foreach (var book in await _bookRepo.GetAllBooks())
        {
            <div class="row">
                <h4 style="color:brown">@book.Title</h4>
            </div>
        }



    </div>

</section>

<div class="content">
    <div class="container">

        <div class="row">

            @*@await Component.InvokeAsync("TopBooks",new { count=3 })*@
            <vc:top-books count="2"></vc:top-books>

            @*@for (var i = 0; i < 3; i++)
                {
                    <div class="col-xs-12 col-sm-4">
                        <partial name="_bookThumbnail" model="new BookModel()" />
                    </div>
                }*@

            @*<div class="col-xs-12 col-sm-4" style="padding-top:10px;">
                    @Html.Partial("_bookThumbnail", new BookModel())
                </div>

                <div class="col-xs-12 col-sm-4" style="padding-top:10px;">
                    @await Html.PartialAsync("_bookThumbnail", new BookModel())
                </div>

                <div class="col-xs-12 col-sm-4" style="padding-top:10px;">
                    @{
                        Html.RenderPartial("_bookThumbnail", new BookModel());
                    }
                </div>


                <div class="col-xs-12 col-sm-4" style="padding-top:15px;">
                    @{
                        await Html.RenderPartialAsync("_bookThumbnail", new BookModel());
                    }
                </div>*@


        </div>
    </div>
</div>

@section JScript{
    <script>
        $(document).ready(function () {
            $("#clickme").click(function () {
                alert("Search Books");
            });
        })
    </script>
}